Rules for missing 'return' and 'param'
AlWoSp/lua-language-server-by-sumneko pull request #3
Opened 2023-03-27 14:41 UTC by wetzlmaier

2023-04-04 06:38 UTC, AlWoSp requested changes

2023-04-04 11:33 UTC, wetzlmaier commented on locale/zh-tw/script.lua
> +DIAG_MISSING_GLOBAL_DOC               =
added comment

2023-04-04 11:33 UTC, wetzlmaier commented on test/diagnostics/missing-return-doc.lua
> +TEST [[
removed empty tests

2023-04-13 07:05 UTC, wetzlmaier commented on locale/en-us/setting.lua
> +'Missing documentation for globals.'
I have adapted the text according to the three rules

2023-04-13 07:08 UTC, wetzlmaier commented on locale/en-us/setting.lua
> +'Missing @return annotation.'
settings.lua = description of the rule
script.lua = linter messages

2023-04-13 07:11 UTC, wetzlmaier commented on locale/en-us/setting.lua
>  'Enable diagnostics for function calls where the number of arguments is less than the number of annotated function parameters.'
This file is not mine. Should I change the message?

2023-04-13 07:21 UTC, wetzlmaier commented on locale/en-us/setting.lua
> +'Missing @param annotation.'
setting.lua = description of the rule
name of function/parameter will be displayed (script.lua)

2023-04-13 11:11 UTC, wetzlmaier commented on locale/en-us/setting.lua
>  'Enable diagnostics for function calls where the number of arguments is less than the number of annotated function parameters.'
"function calls" is correct

2023-04-13 13:37 UTC, wetzlmaier commented on locale/en-us/setting.lua
> +config.diagnostics['missing-global-doc']    =
an additional task is ok

2023-04-13 13:53 UTC, AlWoSp approved these changes

2023-04-19 14:10 UTC, AlWoSp requested changes

2023-04-19 14:23 UTC, AlWoSp approved these changes

2023-04-19 14:49 UTC, merged